---
title: "Future_weather_analysis"
author: "Ellen Maas"
date: "2023-02-10"
output: html_document
description: "Compares the observed historical weather data with each future"
"projection scenario to see how closely it matches."
"**NOTE:  See also 'Weather comparisons_NOAA_PRISM','Perform_Weather_Analysis-NM2'"
"'2_Correlate Kalamazoo and Detroit weather' and 'Perform_Weather_Analysis'."
---

```{r setup, include=FALSE}
rm(list=ls())
knitr::opts_chunk$set(echo = TRUE)
```

```{r libraries, message=FALSE, include=FALSE}
library(readxl)
library(tidyverse)
library(ggplot2)
library(magrittr)
library(lubridate)
library(dplyr)

```

```{r constants}
#
kbs_experiment_start_year <- 2003
kbs_experiment_end_year <- 2021
kbs_experiment_start_date <- "2003-01-01"
kbs_experiment_end_date <- "2021-12-31"
kbs_fut_weather_path <- paste0("Data/CMIP6/KBS/")
kbs_daycent_path <- paste0("Daycent/KBS/")
lrf_experiment_start_year <- 2003
lrf_experiment_end_year <- 2010
lrf_experiment_start_date <- "2003-01-01"
lrf_experiment_end_date <- "2010-12-31"
lrf_fut_weather_path <- paste0("Data/CMIP6/LRF/")
lrf_daycent_path <- paste0("Daycent/LRF/")
end_fut_period_year <- 2050
end_fut_period_date <- "2049-12-31"
end_exp_period_year <- 2021

# 12-color palette with grey and black. Colors in order are:
#[1]black, [2]dark blue, [3]mint green, [4]light blue, [5]grey,
#[6]pink, [7]red, [8]orange, [9]yellow, [10]mauve, [11]royal blue,
#[12]forest green
cbPalette12 <- c("#000000","#0072B2","#009E73","#56B4E9","#999999",
                "#CC79A7","#D55E00","#E69F00","#F0E442","#882255",
                "#332288","#0B6329"
                )
                         

```

```{r KBS import, include=FALSE}

# Historical

## Use Daycent weather for historical, over the experimental period
#hist <- read.table(paste0("C:/Users/edmaas/Documents/Modeling/Daycent/",site_name,"/basic_exp.wth")) 
kbs_hist_exp <- read.table(paste0("../../",kbs_daycent_path,"/basic_exp.wth"))
colnames(kbs_hist_exp) <- c("day","month","year","dayofyear","h_tmax","h_tmin","h_rain_cm")
kbs_hist_exp$date=make_date(kbs_hist_exp$year, kbs_hist_exp$month, kbs_hist_exp$day)

# Future

## Use Daycent weather for historical, over the experimental period
kbs_baseln <- read.table(paste0("../../",kbs_daycent_path,"/basic_1.wth"))
colnames(kbs_baseln) <- c("day","month","year","dayofyear","bl_tmax","bl_tmin","bl_rain_cm")
kbs_baseln <- kbs_baseln[kbs_baseln$year<=end_fut_period_year,]
kbs_baseln$date=make_date(kbs_baseln$year, kbs_baseln$month, kbs_baseln$day)

## CMIPs
kbs_gfdl_low_raw <- read.csv("KBS/fut_clim_scenario_2_reanal.csv")
kbs_gfdl_low <- kbs_gfdl_low_raw %>%
  select(day,month,year,dayofyear,mint_C,maxt_C,rain_cm)
colnames(kbs_gfdl_low) <- c("day","month","year","dayofyear","gl_tmin","gl_tmax","gl_rain_cm")
kbs_gfdl_low$date=make_date(kbs_gfdl_low$year, kbs_gfdl_low$month, kbs_gfdl_low$day)

kbs_gfdl_high_raw <- read.csv("KBS/fut_clim_scenario_3_reanal.csv")
kbs_gfdl_high <- kbs_gfdl_high_raw %>%
  select(day,month,year,dayofyear,mint_C,maxt_C,rain_cm)
colnames(kbs_gfdl_high) <- c("day","month","year","dayofyear","gh_tmin","gh_tmax","gh_rain_cm")
kbs_gfdl_high$date=make_date(kbs_gfdl_high$year, kbs_gfdl_high$month, kbs_gfdl_high$day)

kbs_ukesm_low_raw <- read.csv("KBS/fut_clim_scenario_4_reanal.csv")
kbs_ukesm_low <- kbs_ukesm_low_raw %>%
  select(day,month,year,dayofyear,mint_C,maxt_C,rain_cm)
colnames(kbs_ukesm_low) <- c("day","month","year","dayofyear","ul_tmin","ul_tmax","ul_rain_cm")
kbs_ukesm_low$date=make_date(kbs_ukesm_low$year, kbs_ukesm_low$month, kbs_ukesm_low$day)

kbs_ukesm_high_raw <- read.csv("KBS/fut_clim_scenario_5_reanal.csv")
kbs_ukesm_high <- kbs_ukesm_high_raw %>%
  select(day,month,year,dayofyear,mint_C,maxt_C,rain_cm)
colnames(kbs_ukesm_high) <- c("day","month","year","dayofyear","uh_tmin","uh_tmax","uh_rain_cm")
kbs_ukesm_high$date=make_date(kbs_ukesm_high$year, kbs_ukesm_high$month, kbs_ukesm_high$day)

```

```{r lrf import, include=FALSE}

# Historical

## Use Daycent weather for historical, over the experimental period
#hist <- read.table(paste0("C:/Users/edmaas/Documents/Modeling/Daycent/",site_name,"/basic_exp.wth")) 
lrf_hist_exp <- read.table(paste0("../../",lrf_daycent_path,"/basic_exp.wth"))
colnames(lrf_hist_exp) <- c("day","month","year","dayofyear","h_tmax","h_tmin","h_rain_cm")
lrf_hist_exp$date=make_date(lrf_hist_exp$year, lrf_hist_exp$month, lrf_hist_exp$day)

# Future

## Use Daycent weather for historical, over the experimental period
lrf_baseln <- read.table(paste0("../../",lrf_daycent_path,"/basic_1.wth"))
colnames(lrf_baseln) <- c("day","month","year","dayofyear","bl_tmax","bl_tmin","bl_rain_cm")
lrf_baseln <- lrf_baseln[lrf_baseln$year<=end_fut_period_year,]
lrf_baseln$date=make_date(lrf_baseln$year, lrf_baseln$month, lrf_baseln$day)

## CMIPs
lrf_gfdl_low_raw <- read.csv("LRF/fut_clim_scenario_2_reanal.csv") 
lrf_gfdl_low <- lrf_gfdl_low_raw %>%
  select(day,month,year,dayofyear,mint_C,maxt_C,rain_cm)
colnames(lrf_gfdl_low) <- c("day","month","year","dayofyear","gl_tmin","gl_tmax","gl_rain_cm")
lrf_gfdl_low$date=make_date(lrf_gfdl_low$year, lrf_gfdl_low$month, lrf_gfdl_low$day)

lrf_gfdl_high_raw <- read.csv("LRF/fut_clim_scenario_3_reanal.csv")
lrf_gfdl_high <- lrf_gfdl_high_raw %>%
  select(day,month,year,dayofyear,mint_C,maxt_C,rain_cm)
colnames(lrf_gfdl_high) <- c("day","month","year","dayofyear","gh_tmin","gh_tmax","gh_rain_cm")
lrf_gfdl_high$date=make_date(lrf_gfdl_high$year, lrf_gfdl_high$month, lrf_gfdl_high$day)
mean(lrf_gfdl_high$gh_rain_cm)

lrf_ukesm_low_raw <- read.csv("LRF/fut_clim_scenario_4_reanal.csv")
lrf_ukesm_low <- lrf_ukesm_low_raw %>%
  select(day,month,year,dayofyear,mint_C,maxt_C,rain_cm)
colnames(lrf_ukesm_low) <- c("day","month","year","dayofyear","ul_tmin","ul_tmax","ul_rain_cm")
lrf_ukesm_low$date=make_date(lrf_ukesm_low$year, lrf_ukesm_low$month, lrf_ukesm_low$day)

lrf_ukesm_high_raw <- read.csv("LRF/fut_clim_scenario_5_reanal.csv")
lrf_ukesm_high <- lrf_ukesm_high_raw %>%
  select(day,month,year,dayofyear,mint_C,maxt_C,rain_cm)
colnames(lrf_ukesm_high) <- c("day","month","year","dayofyear","uh_tmin","uh_tmax","uh_rain_cm")
lrf_ukesm_high$date=make_date(lrf_ukesm_high$year, lrf_ukesm_high$month, lrf_ukesm_high$day)

```


```{r tmin_group_data}

kbs_tmin_df <- merge(merge(merge(merge(merge(kbs_hist_exp[,c("date","h_tmin")],
                                         kbs_baseln[,c("date","bl_tmin")],
                                         by="date",
                                         all=TRUE),
                                   kbs_gfdl_low[,c("date","gl_tmin")],
                                   by="date",
                                   all=TRUE),
                             kbs_gfdl_high[,c("date","gh_tmin")],
                             by="date",
                             all=TRUE),
                       kbs_ukesm_low[,c("date","ul_tmin")],
                       by="date",
                       all=TRUE),
                 kbs_ukesm_high[,c("date","uh_tmin")],
                 by="date",
                 all=TRUE) %>%
  mutate(site_name="KBS",
         clim_var="Min Temp")
colnames(kbs_tmin_df) <- c("Date","Historical","Baseline","GFDL_Low","GFDL_High",
                       "UKESM_Low","UKESM_High","SiteName","ClimateVariable")

kbs_tmin_piv <- pivot_longer(kbs_tmin_df, c(-Date,-SiteName,-ClimateVariable),
                         names_to = "source",
                         values_to = "val")

lrf_tmin_df <- merge(merge(merge(merge(merge(lrf_hist_exp[,c("date","h_tmin")],
                                         lrf_baseln[,c("date","bl_tmin")],
                                         by="date",
                                         all=TRUE),
                                   lrf_gfdl_low[,c("date","gl_tmin")],
                                   by="date",
                                   all=TRUE),
                             lrf_gfdl_high[,c("date","gh_tmin")],
                             by="date",
                             all=TRUE),
                       lrf_ukesm_low[,c("date","ul_tmin")],
                       by="date",
                       all=TRUE),
                 lrf_ukesm_high[,c("date","uh_tmin")],
                 by="date",
                 all=TRUE) %>%
  mutate(site_name="LRF",
         clim_var="Min Temp")
colnames(lrf_tmin_df) <- c("Date","Historical","Baseline","GFDL_Low","GFDL_High",
                       "UKESM_Low","UKESM_High","SiteName","ClimateVariable")

lrf_tmin_piv <- pivot_longer(lrf_tmin_df, c(-Date,-SiteName,-ClimateVariable),
                         names_to = "source",
                         values_to = "val")

tmin_piv <- rbind(kbs_tmin_piv,lrf_tmin_piv)

```

```{r tmax_group_data}

kbs_tmax_df <- merge(merge(merge(merge(merge(kbs_hist_exp[,c("date","h_tmax")],
                                         kbs_baseln[,c("date","bl_tmax")],
                                         by="date",
                                         all=TRUE),
                                   kbs_gfdl_low[,c("date","gl_tmax")],
                                   by="date",
                                   all=TRUE),
                             kbs_gfdl_high[,c("date","gh_tmax")],
                             by="date",
                             all=TRUE),
                       kbs_ukesm_low[,c("date","ul_tmax")],
                       by="date",
                       all=TRUE),
                 kbs_ukesm_high[,c("date","uh_tmax")],
                 by="date",
                 all=TRUE) %>%
  mutate(site_name="KBS",
         clim_var="Max Temp")
colnames(kbs_tmax_df) <- c("Date","Historical","Baseline","GFDL_Low","GFDL_High",
                       "UKESM_Low","UKESM_High","SiteName","ClimateVariable")

kbs_tmax_piv <- pivot_longer(kbs_tmax_df, c(-Date,-SiteName,-ClimateVariable),
                         names_to = "source",
                         values_to = "val")

lrf_tmax_df <- merge(merge(merge(merge(merge(lrf_hist_exp[,c("date","h_tmax")],
                                         lrf_baseln[,c("date","bl_tmax")],
                                         by="date",
                                         all=TRUE),
                                   lrf_gfdl_low[,c("date","gl_tmax")],
                                   by="date",
                                   all=TRUE),
                             lrf_gfdl_high[,c("date","gh_tmax")],
                             by="date",
                             all=TRUE),
                       lrf_ukesm_low[,c("date","ul_tmax")],
                       by="date",
                       all=TRUE),
                 lrf_ukesm_high[,c("date","uh_tmax")],
                 by="date",
                 all=TRUE) %>%
  mutate(site_name="LRF",
         clim_var="Max Temp")
colnames(lrf_tmax_df) <- c("Date","Historical","Baseline","GFDL_Low","GFDL_High",
                       "UKESM_Low","UKESM_High","SiteName","ClimateVariable")

lrf_tmax_piv <- pivot_longer(lrf_tmax_df, c(-Date,-SiteName,-ClimateVariable),
                         names_to = "source",
                         values_to = "val")

tmax_piv <- rbind(kbs_tmax_piv,lrf_tmax_piv)

```

```{r rain_cm_group_data}

kbs_rain_cm_df <- merge(merge(merge(merge(merge(kbs_hist_exp[,c("date","h_rain_cm")],
                                         kbs_baseln[,c("date","bl_rain_cm")],
                                         by="date",
                                         all=TRUE),
                                   kbs_gfdl_low[,c("date","gl_rain_cm")],
                                   by="date",
                                   all=TRUE),
                             kbs_gfdl_high[,c("date","gh_rain_cm")],
                             by="date",
                             all=TRUE),
                       kbs_ukesm_low[,c("date","ul_rain_cm")],
                       by="date",
                       all=TRUE),
                 kbs_ukesm_high[,c("date","uh_rain_cm")],
                 by="date",
                 all=TRUE) %>%
  mutate(site_name="KBS",
         clim_var="Rain")
colnames(kbs_rain_cm_df) <- c("Date","Historical","Baseline","GFDL_Low","GFDL_High",
                       "UKESM_Low","UKESM_High","SiteName","ClimateVariable")

kbs_rain_cm_piv <- pivot_longer(kbs_rain_cm_df, c(-Date,-SiteName,-ClimateVariable),
                         names_to = "source",
                         values_to = "val")

lrf_rain_cm_df <- merge(merge(merge(merge(merge(lrf_hist_exp[,c("date","h_rain_cm")],
                                         lrf_baseln[,c("date","bl_rain_cm")],
                                         by="date",
                                         all=TRUE),
                                   lrf_gfdl_low[,c("date","gl_rain_cm")],
                                   by="date",
                                   all=TRUE),
                             lrf_gfdl_high[,c("date","gh_rain_cm")],
                             by="date",
                             all=TRUE),
                       lrf_ukesm_low[,c("date","ul_rain_cm")],
                       by="date",
                       all=TRUE),
                 lrf_ukesm_high[,c("date","uh_rain_cm")],
                 by="date",
                 all=TRUE) %>%
  mutate(site_name="LRF",
         clim_var="Rain")
colnames(lrf_rain_cm_df) <- c("Date","Historical","Baseline","GFDL_Low","GFDL_High",
                       "UKESM_Low","UKESM_High","SiteName","ClimateVariable")

lrf_rain_cm_piv <- pivot_longer(lrf_rain_cm_df, c(-Date,-SiteName,-ClimateVariable),
                         names_to = "source",
                         values_to = "val")

rain_cm_piv <- rbind(kbs_rain_cm_piv,lrf_rain_cm_piv)

```

```{r combine}

alldata_piv <- rbind(tmin_piv,tmax_piv,rain_cm_piv) %>%
  filter(Date<as.Date(end_fut_period_date))
                     

```


```{r graph}

  g_temp <- alldata_piv[alldata_piv$ClimateVariable %in% c("Max Temp","Min Temp"),] %>%
    ggplot(aes(x=Date, y=val, color=source, show.legend=TRUE)) +
    # geom_point(show.legend=TRUE) +
    xlab("Year") +
    ylab(expression('Temperature ( ' ^o*'C)')) +
   # ylim(0,3) +
    ggtitle("Historical Temperature and Future Projections") +
    geom_smooth(method='lm', formula= y~x, se=FALSE, aes(colour = source)
                ,linewidth=0.75) +
    scale_color_manual(labels=c("Baseline","GFDL_High","GFDL_Low",
                                "Historical","UKESM_High","UKESM_Low"),
                       values=cbPalette12[c(8,2,4,1,10,6)],
                       name="Climate Model") +
    facet_grid(ClimateVariable~SiteName) +
    theme_classic(base_family = "serif", base_size = 16) +
    theme(panel.background = element_blank(),
          panel.border = element_rect(colour = "darkgrey", fill=NA),
          strip.background = element_blank(),
          axis.line = element_line(),
          legend.position = "right",
          legend.key = element_blank())
  
  g_temp
  

    g_rain <- alldata_piv[alldata_piv$ClimateVariable == "Rain",] %>%
    ggplot(aes(x=Date, y=val, color=source, show.legend=TRUE)) +
    # geom_point(show.legend=TRUE) +
    xlab("Year") +
    ylab(expression('Precipitation (cm)')) +
   # ylim(0,3) +
    ggtitle("Historical Precipitation and Future Projections") +
    geom_smooth(method='lm', formula= y~x, se=FALSE, aes(colour = source)
                ,linewidth=0.75,na.rm=TRUE) +
    scale_color_manual(labels=c("Baseline","GFDL_High","GFDL_Low",
                                "Historical","UKESM_High","UKESM_Low"),
                       values=cbPalette12[c(8,2,4,1,10,6)],
                       name="Climate Model") +
    facet_wrap(~SiteName) +
    theme_classic(base_family = "serif", base_size = 16) +
    theme(panel.background = element_blank(),
          panel.border = element_rect(colour = "darkgrey", fill=NA),
          strip.background = element_blank(),
          axis.line = element_line(),
          legend.position = "right",
          legend.key = element_blank())
  
  g_rain

    ggsave(filename="../../Comb_results_2050/pub_Future_temperature.jpg",
         plot=g_temp, width=8, height=6, dpi=300)
    ggsave(filename="../../Comb_results_2050/pub_Future_precipitation.jpg",
         plot=g_rain, width=9, height=4, dpi=300)
 
```
